// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoricbcevlvbvynejrsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvcmljYmNldmx2YnZ5bmVqcnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODM4MzUsImV4cCI6MjA3MTE1OTgzNX0.Eybm_LXQNM8Nfbjt65LzRR8V5LsTrOThXqWYN5DUZPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});